import { useEffect, useState } from "react";
import MeetupList from "../components/meetups/MeetupList";

const DUMMY_MEETUPS = [
  {
    id: "m1",
    title: "A First Meetup",
    image:
      "https://media.istockphoto.com/photos/the-leaning-tower-in-pisa-picture-id929861782?k=20&m=929861782&s=612x612&w=0&h=fPhTAo1b8DGV98Mg-I2MJVtiYa9d83HvUCCE9qY4f-w=",
    address: "Some address 5, 12345 Some City",
    description: "This is the first Meetup",
  },
  {
    id: "m2",
    title: "A Second Meetup",
    image:
      "https://media.istockphoto.com/photos/the-leaning-tower-in-pisa-picture-id929861782?k=20&m=929861782&s=612x612&w=0&h=fPhTAo1b8DGV98Mg-I2MJVtiYa9d83HvUCCE9qY4f-w=",
    address: "Some address 5, 12345 Some City",
    description: "This is the Second Meetup",
  },
];

function HomePage() {
    const [loadedMeetups, setLoadedMeetups] = useState([])//om first render, the state is an empty array
    useEffect(() => {
      //fetch http request
      setLoadedMeetups(DUMMY_MEETUPS)
    }, [])
    //after useEffect updates state, whole component rerenders bcos state changed.

    // NB: Because of this two render cycles, we have a problem with search engine optimization.  

    // WHY?

    // Because on inspection of the page source, we get an empty undeordered list(from meetuplist) because state was initially an empty array on the first load. 

    // This is because the prerendered HTML page generated by nextjs does not wait for the second cycle and that's where page pre-rendering comes in

    return <MeetupList meetups={loadedMeetups} />        
}

export default HomePage;